from math import *
# print(abs(-5))
# print(pow(2,3))
# print(min(20,10))
# print(max(20,10))
# print(sqrt(25))
# print(round(3.4))
# print(floor(3.7))
# print(ceil(3.7))
absolute = abs(-5)
minimum = min(20,5,30)
maximum = max(10,20,30)
power  = pow(2,3)
root = sqrt(25)
r = round(3.5)
f = floor(9.7)
c = ceil(9.4)

print(absolute)
print(maximum)
print(minimum)
print(power)
print(root)
print(r)
print(f)
print(c)