n=int(input())
l=int(input())
ch=(input())
f=float(input())
d=float(input())
# n,l,ch,f,d=(int(input()),int(input()),(input()),float(input()),float(input()))
print(n)
print(l)
print(ch)
print(f)
print(d)