p1 = Person("Bob", 21, "Student")
# print("=================================")
# p1.pushVaccine(astra)
# print("=================================")
# p1.showDetail()
# print("=================================")
# p1.pushVaccine(sin, "2nd Dose")
# print("=================================")
# p1.pushVaccine(astra, "2nd Dose")
# print("=================================")
# p1.showDetail()
# print("=================================")
# p2 = Person("Carol", 23, "Actor")
# print("=================================")
# p2.pushVaccine(sin)
# print("=================================")
# p3 = Person("David", 34)
# print("=================================")
# p3.pushVaccine(modr)
# print("=================================")
# p3.showDetail()
# print("=================================")
# p3.pushVaccine(modr, "2nd Dose")
